name: Desplegar MkDocs a GitHub Pages

on:
  push:
    branches:
      - jedi  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar MkDocs y tema Material
        run: pip install mkdocs mkdocs-material

      - name: Construir y desplegar en GitHub Pages
        run: mkdocs gh-deploy -f docu/mkdocs.yml --force
